### ISSUE TITLE
interpret saves h5 files extremely slowly

### ISSUE THREAD

**Issue by mmtrebuchet** [kundajelab/basepairmodels#13]
For a run of about 12k regions, each 1 kb wide, running the interpret script takes about as long to run through the regions and generate scores as it does to save those scores (about 1 GB) to disk. Since this is a single call to DeepDish, I wonder if this could be optimized in some way to write those files much faster.

**Comment by mmtrebuchet** [comment]
(It takes about half an hour to write the h5 files on my system)

**Comment by zahoorz** [comment]
use the shap_scores script
https://github.com/kundajelab/basepairmodels/blob/master/basepairmodels/cli/shap_scores.py
