### ISSUE TITLE
Is BPNet appropriate for modeling histone modification ChIP-seq data?

### ISSUE THREAD

**Issue by stephenrong** [kundajelab/basepairmodels#37]
Such as H3K27ac, H3K4me3, and H3K4me1 data. Or would be it inappropriate to use for some reason, such as a larger average peak size, some technical bias I might not be aware of, or non-discoverability of the underlying regulatory grammar, compared to TF ChIP-seq?

**Comment by akundaje** [comment]
No it will not work well as is on histone marks. We'll have a powerful
histone mark model out in a few months.

**Comment by stephenrong** [comment]
Thanks, looking forward to it!
